config/routes.rb
Photogallery::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :albums, only: [:show] do
    member do
      get '/:theme', action: :show, constraints: { theme: /video|folio|azur/ }, as: :theme
    end
  end

  root to: 'albums#index'

  

end

app/models/album.rb
class Album < ActiveRecord::Base
  include DefaultUser

  cattr_accessor :current_user

  belongs_to :user
  has_many :videos

  validates :title, presence: true
  validates :image, presence: true

  def self.visible
    if current_user.try(:is_admin?)
      all
    else
     where(is_visible: true)
    end
  end

  private

  def self.search(query)
    query = query.split(' ').map { |word| "%#{word}%" }
    if query.count == 1 && query.first[1..-2].to_i > 0
      date = Time.parse("01.01.#{query.first[1..-2].to_i}")
      where(date: date.at_beginning_of_year..date.at_end_of_year)
    else
      where(self.arel_table[:title].matches_any(query).or(self.arel_table[:description].matches_any(query)))
    end
  end
end

app/models/concerns/default_user.rb
module DefaultUser
  extend ActiveSupport::Concern

  included do
    validates :user_id, presence: true

    before_validation :set_current_user
  end

  private

  def set_current_user
    if current_user.try(:is_admin?)
      self.user_id = current_user.try(:id) unless self.user_id
    else
      self.user_id = current_user.try(:id)
    end
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base

  cattr_accessor :current_user

  before_destroy :prevent_delete
  before_create :prevent_create

  private

  def prevent_delete
    false
  end

  def prevent_create
    if current_user.try(:is_admin?)
      false
    else
      true
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :albums
  has_many :videos

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  include DefaultUser

  cattr_accessor :current_user

  belongs_to :album

  validates :link, presence: true, format:  { with: /vimeo|youtube/ }

  before_save :set_title

  private

  def set_title
    self.title = link unless title?
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.visible.order('date DESC, created_at DESC')
    @albums = @albums.search(params[:query]) if params[:query].present?
  end

  def show
    @album = Album.find(params[:id])
    params[:theme] ||= 'twelve'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_current_user
  before_filter :get_settings

  private

  def get_settings
    @setting = Setting.first
  end

  def set_current_user
    Album.current_user = current_user
    Video.current_user = current_user
    Setting.current_user = current_user
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.haml
.album
  = link_to image_tag('stub.png', data: {id: album.image}), "#{album.flickr.present? ? album_path(album) : theme_album_path(album, 'video')}", class: "image #{cycle('odd', 'even')}"
  - if album.videos.any?
    .video= link_to image_tag('icon_video.png'), theme_album_path(album, 'video'), title: 'Видео'
  - if album.flickr.present?
    .theme
      = link_to image_tag('icon_twelve.png'), album_path(album), title: 'Просмотр фотографий  в полный размер'
      = link_to image_tag('icon_azur.png'), theme_album_path(album, 'azur'), title: 'Просмотр фотографий в оригинальный размер'
      = link_to image_tag('icon_folio.png'), theme_album_path(album, 'folio'), title: 'Миниатюры и полноэкранный режим'
  .caption
    .title= album.title
    - if album.description.present?
      .description= album.description
    - if album.date
      .date= localize(album.date, format: :date)

app/views/albums/index.html.haml
- content_for :page_title do
  Альбомы
  .search
    %form{action: root_path, method: 'get'}
      = text_field_tag :query, params[:query], placeholder: 'Поиск'

#albums.clearfix= render partial: 'album', collection: @albums

app/views/albums/show.html.haml
- content_for :page_title do
  .back= link_to image_tag('back.png'), root_path, title: 'Вернуться к выбору альбомов'
  = @album.title
  .theme
    - if @album.videos.any?
      = link_to image_tag('icon_video.png'), theme_album_path(@album, 'video'), title: 'Видео', class: "video #{params[:theme] == 'video' ? 'active' : ''}"
    - if @album.flickr.present?
      = link_to image_tag('icon_twelve.png'), album_path(@album), class: params[:theme] == 'twelve' ? 'active' : '', title: 'Просмотр фотографий  в полный размер'
      = link_to image_tag('icon_azur.png'), theme_album_path(@album, 'azur'), class: params[:theme] == 'azur' ? 'active' : '', title: 'Просмотр фотографий в оригинальный размер'
      = link_to image_tag('icon_folio.png'), theme_album_path(@album, 'folio'), class: params[:theme] == 'folio' ? 'active' : '', title: 'Миниатюры и полноэкранный режим'

#album{class: params[:theme]}
  - if params[:theme] == 'video'
    - @album.videos.each do |video|
      = link_to '<span class="video">Video</span>'.html_safe, video.link

- if params[:theme] == 'video'
  :javascript
    Galleria.run('#album');
- elsif params[:theme] == 'folio'
  :javascript
    Galleria.run('#album', {
        autoplay: false,
        flickr: "set:#{@album.flickr}",
        flickrOptions: {
            sort: 'date-posted-asc',
            thumbSize: 'small',
            imageSize: 'original',
            max: 100
        }
    });
- else
  :javascript
    Galleria.run('#album', {
        autoplay: parseInt("#{@setting.autoplay * 1000}"),
        flickr: "set:#{@album.flickr}",
        flickrOptions: {
            sort: 'date-posted-asc',
            thumbSize: 'small',
            imageSize: 'original',
            max: 100
        }
    });

app/views/layouts/_head.haml
%head
  %title Photogallery
  = javascript_include_tag "application"
  = render 'layouts/theme'
  = stylesheet_link_tag    "application", media: "all"
  = csrf_meta_tags
  %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
  %meta{:content => "width=device-width", :name => "viewport"}/

  :css
    body {
    }

app/views/layouts/_theme.haml
- if controller_name == 'albums' && action_name == 'show'
  - if params[:theme] == 'video'
    = stylesheet_link_tag    "themes/azur/galleria.azur", media: "all"
    = javascript_include_tag "themes/azur/galleria.azur"
  - else
    = stylesheet_link_tag    "themes/#{params[:theme]}/galleria.#{params[:theme]}", media: "all"
    = javascript_include_tag "themes/#{params[:theme]}/galleria.#{params[:theme]}"

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    - if current_user.try(:is_admin?)
      = link_to image_tag('door.png'), rails_admin_path, id: 'admin'
    #wrapper
      #header
        %h1.page-title= yield :page_title
      #content
        = yield